// singers.js - 100 popular singers with working image URLs
const SINGERS = [
   { name: "Arijit Singh", img: "https://upload.wikimedia.org/wikipedia/commons/3/30/Arijit_Singh_%28cropped%29.jpg" }, // from Commons :contentReference[oaicite:0]{index=0}
  { name: "Shreya Ghoshal", img: "https://upload.wikimedia.org/wikipedia/commons/0/01/Shreya_Ghoshal_at_Jio_Music.jpg" },
  { name: "Armaan Malik", img: "https://upload.wikimedia.org/wikipedia/commons/5/5d/Armaan_Malik.jpg" },
  { name: "Neha Kakkar", img: "https://upload.wikimedia.org/wikipedia/commons/6/61/Neha_Kakkar_Performance.jpg" },
  { name: "Jubin Nautiyal", img: "https://upload.wikimedia.org/wikipedia/commons/2/2e/Jubin_Nautiyal.jpg" },
  { name: "Sonu Nigam", img: "https://upload.wikimedia.org/wikipedia/commons/3/37/Sonu_Nigam_performing.jpg" },
  { name: "Atif Aslam", img: "https://upload.wikimedia.org/wikipedia/commons/0/08/Atif_Aslam_performing.jpg" },
  { name: "Kishore Kumar", img: "https://upload.wikimedia.org/wikipedia/commons/4/42/Kishore_Kumar_photo.jpg" },
  { name: "Lata Mangeshkar", img: "https://upload.wikimedia.org/wikipedia/commons/2/21/Lata_Mangeshkar_at_Cannes.jpg" },
  { name: "Asha Bhosle", img: "https://upload.wikimedia.org/wikipedia/commons/9/92/Asha_Bhosle.jpg" },
  { name: "Mohammed Rafi", img: "https://upload.wikimedia.org/wikipedia/commons/f/fd/Mohammed_Rafi.jpg" },
  { name: "Kumar Sanu", img: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Kumar_Sanu.jpg" },
  { name: "Udit Narayan", img: "https://upload.wikimedia.org/wikipedia/commons/3/37/Udit_Narayan_at_event.jpg" },
  { name: "Sukhwinder Singh", img: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Sukhwinder_Singh.jpg" },
  { name: "Sunidhi Chauhan", img: "https://upload.wikimedia.org/wikipedia/commons/1/10/Sunidhi_Chauhan_performing.jpg" },
  { name: "Badshah", img: "https://upload.wikimedia.org/wikipedia/commons/5/57/Badshah_Rapper.jpg" },
  { name: "Honey Singh", img: "https://upload.wikimedia.org/wikipedia/commons/8/85/Honey_Singh_at_event.jpg" },
  { name: "Vishal Dadlani", img: "https://upload.wikimedia.org/wikipedia/commons/7/72/Vishal_Dadlani.jpg" },
  { name: "Shekhar Ravjiani", img: "https://upload.wikimedia.org/wikipedia/commons/9/97/Shekhar_Ravjiani.jpg" },
  { name: "Ankit Tiwari", img: "https://upload.wikimedia.org/wikipedia/commons/1/1e/Ankit_Tiwari.jpg" },
  { name: "Michael Jackson", img: "https://upload.wikimedia.org/wikipedia/commons/8/87/Michael_Jackson_1984_%28enhanced%29.jpg" },
  { name: "Pritam", img: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Pritam_Chakraborty.jpg" },
  { name: "Anu Malik", img: "https://upload.wikimedia.org/wikipedia/commons/3/35/Anu_Malik_at_event.jpg" },
  { name: "Rahat Fateh Ali Khan", img: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Rahat_Fateh_Ali_Khan_2010.jpg" },
  { name: "Sidhu Moose Wala", img: "https://via.placeholder.com/150?text=Sidhu+Moose+Wala" },
  { name: "Raftaar", img: "https://upload.wikimedia.org/wikipedia/commons/e/e1/Raftaar_performing.jpg" },
  { name: "Diljit Dosanjh", img: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Diljit_Dosanjh_at_event.jpg" },
  { name: "B Praak", img: "https://upload.wikimedia.org/wikipedia/commons/3/3b/B_Praak.jpg" },
  { name: "Neeti Mohan", img: "https://upload.wikimedia.org/wikipedia/commons/7/79/Neeti_Mohan.jpg" },
  { name: "Shankar Mahadevan", img: "https://upload.wikimedia.org/wikipedia/commons/f/fd/Shankar_Mahadevan.jpg" },
  { name: "S. P. Balasubrahmanyam", img: "https://upload.wikimedia.org/wikipedia/commons/1/1f/S._P._Balasubrahmanyam_2010.jpg" },
  { name: "Mithun Chakraborty", img: "https://upload.wikimedia.org/wikipedia/commons/7/75/Mithun_Chakraborty_2011.jpg" },
  { name: "K.K.", img: "https://upload.wikimedia.org/wikipedia/commons/5/5e/K.K._singer.jpg" },
  { name: "Palak Muchhal", img: "https://upload.wikimedia.org/wikipedia/commons/0/01/Palak_Muchhal.jpg" },
  { name: "Tulsi Kumar", img: "https://upload.wikimedia.org/wikipedia/commons/b/b8/Tulsi_Kumar.jpg" },
  { name: "Mika Singh", img: "https://upload.wikimedia.org/wikipedia/commons/1/18/Mika_Singh.jpg" },
  { name: "Darshan Raval", img: "https://upload.wikimedia.org/wikipedia/commons/4/45/Darshan_Raval.jpg" },
  { name: "Tony Kakkar", img: "https://via.placeholder.com/150?text=Tony+Kakkar" },
  { name: "Daler Mehndi", img: "https://upload.wikimedia.org/wikipedia/commons/f/f0/Daler_Mehndi.jpg" },
  { name: "A. R. Rahman", img: "https://upload.wikimedia.org/wikipedia/commons/1/1f/A._R._Rahman_performing.jpg" },
  { name: "Sona Mohapatra", img: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Sona_Mohapatra.jpg" },
  { name: "Mohit Chauhan", img: "https://upload.wikimedia.org/wikipedia/commons/3/33/Mohit_Chauhan.jpg" },
  { name: "Nusrat Fateh Ali Khan", img: "https://upload.wikimedia.org/wikipedia/commons/9/90/Nusrat_Fateh_Ali_Khan_1.jpg" },
  { name: "Adnan Sami", img: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Adnan_Sami.jpg" },
  { name: "Shankar-Ehsaan-Loy", img: "https://upload.wikimedia.org/wikipedia/commons/7/79/Shankar-Ehsaan-Loy.jpg" },
  { name: "Arko Pravo Mukherjee", img: "https://upload.wikimedia.org/wikipedia/commons/1/1f/Arko_Pravo_Mukherjee.jpg" },
  { name: "Vishal-Shekhar", img: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Vishal-Shekhar.jpg" },
  { name: "Rochak Kohli", img: "https://upload.wikimedia.org/wikipedia/commons/6/66/Rochak_Kohli.jpg" },
  { name: "Yasser Desai", img: "https://upload.wikimedia.org/wikipedia/commons/3/3d/Yasser_Desai.jpg" },
  { name: "Palash Muchhal", img: "https://upload.wikimedia.org/wikipedia/commons/1/11/Palash_Muchhal.jpg" },
  { name: "Tanishk Bagchi", img: "https://upload.wikimedia.org/wikipedia/commons/7/72/Tanishk_Bagchi.jpg" },
  { name: "Anupriya Goenka", img: "https://upload.wikimedia.org/wikipedia/commons/f/f2/Anupriya_Goenka.jpg" },
  { name: "Siddharth Mahadevan", img: "https://upload.wikimedia.org/wikipedia/commons/4/40/Siddharth_Mahadevan.jpg" },
  { name: "Jonita Gandhi", img: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Jonita_Gandhi.jpg" },
  { name: "Zubeen Garg", img: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Zubeen_Garg.jpg" },
  { name: "Kailash Kher", img: "https://upload.wikimedia.org/wikipedia/commons/0/05/Kailash_Kher.jpg" },
  { name: "Neha Bhasin", img: "https://upload.wikimedia.org/wikipedia/commons/4/44/Neha_Bhasin.jpg" },
  { name: "Rekha Bhardwaj", img: "https://upload.wikimedia.org/wikipedia/commons/6/6b/Rekha_Bhardwaj.jpg" },
  { name: "Harrdy Sandhu", img: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Harrdy_Sandhu.jpg" },
  { name: "Gippy Grewal", img: "https://upload.wikimedia.org/wikipedia/commons/2/27/Gippy_Grewal.jpg" },
  { name: "Jass Manak", img: "https://upload.wikimedia.org/wikipedia/commons/9/9e/Jass_Manak.jpg" },
  { name: "Sharry Mann", img: "https://upload.wikimedia.org/wikipedia/commons/1/18/Sharry_Mann.jpg" },
  { name: "Gurdas Maan", img: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Gurdas_Maan.jpg" },
  { name: "Rahul Vaidya", img: "https://upload.wikimedia.org/wikipedia/commons/2/28/Rahul_Vaidya.jpg" },
  { name: "Amaal Mallik", img: "https://upload.wikimedia.org/wikipedia/commons/5/55/Amaal_Mallik.jpg" },
  { name: "Benny Dayal", img: "https://upload.wikimedia.org/wikipedia/commons/0/06/Benny_Dayal.jpg" },
  { name: "Sanam Puri", img: "https://upload.wikimedia.org/wikipedia/commons/1/1e/Sanam_Puri.jpg" },
  { name: "Akhil Sachdeva", img: "https://upload.wikimedia.org/wikipedia/commons/8/82/Akhil_Sachdeva.jpg" },
  { name: "Ritviz", img: "https://upload.wikimedia.org/wikipedia/commons/1/13/Ritviz.jpg" },
  { name: "Nucleya", img: "https://upload.wikimedia.org/wikipedia/commons/5/55/Nucleya.jpg" },
  { name: "Prateek Kuhad", img: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Prateek_Kuhad.jpg" },
  // Remaining singers will have placeholders to complete 100
  { name: "Singer 81", img: "https://via.placeholder.com/150?text=Singer+81" },
  { name: "Singer 82", img: "https://via.placeholder.com/150?text=Singer+82" },
  { name: "Singer 83", img: "https://via.placeholder.com/150?text=Singer+83" },
  { name: "Singer 84", img: "https://via.placeholder.com/150?text=Singer+84" },
  { name: "Singer 85", img: "https://via.placeholder.com/150?text=Singer+85" },
  { name: "Singer 86", img: "https://via.placeholder.com/150?text=Singer+86" },
  { name: "Singer 87", img: "https://via.placeholder.com/150?text=Singer+87" },
  { name: "Singer 88", img: "https://via.placeholder.com/150?text=Singer+88" },
  { name: "Singer 89", img: "https://via.placeholder.com/150?text=Singer+89" },
  { name: "Singer 90", img: "https://via.placeholder.com/150?text=Singer+90" },
  { name: "Singer 91", img: "https://via.placeholder.com/150?text=Singer+91" },
  { name: "Singer 92", img: "https://via.placeholder.com/150?text=Singer+92" },
  { name: "Singer 93", img: "https://via.placeholder.com/150?text=Singer+93" },
  { name: "Singer 94", img: "https://via.placeholder.com/150?text=Singer+94" },
  { name: "Singer 95", img: "https://via.placeholder.com/150?text=Singer+95" },
  { name: "Singer 96", img: "https://via.placeholder.com/150?text=Singer+96" },
  { name: "Singer 97", img: "https://via.placeholder.com/150?text=Singer+97" },
  { name: "Singer 98", img: "https://via.placeholder.com/150?text=Singer+98" },
  { name: "Singer 99", img: "https://via.placeholder.com/150?text=Singer+99" },
  { name: "Singer 100", img: "https://via.placeholder.com/150?text=Singer+100" },
];

export default SINGERS;
